# Generated by Django 5.2.3 on 2025-07-20 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='describtion',
            new_name='description',
        ),
    ]
